chart_download_ui <- function(id) {
  ns <- shiny::NS(id)
  shiny::tagList(
    shiny::downloadButton(ns("png"), "Download PNG", class = "btn-primary"),
    shiny::tags$span(style = "margin: 0 10px;"),
    shiny::downloadButton(ns("svg"), "Download SVG", class = "btn-success"),
    shiny::tags$span(style = "margin: 0 10px;"),
    shiny::downloadButton(ns("pdf"), "Download PDF", class = "btn-info"),
    shiny::tags$span(style = "margin: 0 10px;"),
    shiny::downloadButton(ns("code"), "Download R Code", class = "btn-secondary")
  )
}

# Convert a value to compact, executable R code without retaining environments.
code_value <- function(x) {
  paste(capture.output(dput(x)), collapse = "\n")
}

readable_data_code <- function(data, object = "chart_data") {
  data <- as.data.frame(data)
  keep <- !grepl("^\\.layer_", names(data))
  data <- data[keep]
  fields <- vapply(names(data), function(name) {
    paste0("  `", name, "` = ", code_value(data[[name]]))
  }, "")
  c(paste0(object, " <- data.frame("), paste0(fields, collapse = ",\n"), ",\n  check.names = FALSE\n)")
}

semantic_chart_code <- function(plot, chart_name) {
  type <- sub("_chart$", "", chart_name)
  type <- sub("_expectation$", "", type)
  supported <- c("run", "line", "bar", "expectation", "trended", "trended_expectation", "cohort")
  if (!type %in% supported && !chart_name %in% c("expectation_chart", "trended_expectation_chart")) return(NULL)
  if (chart_name == "expectation_chart") type <- "expectation"
  if (chart_name == "trended_expectation_chart") type <- "trended"

  data <- if (!inherits(plot$data, "waiver")) as.data.frame(plot$data) else {
    candidates <- lapply(plot$layers, function(x) if (!inherits(x$data, "waiver")) as.data.frame(x$data) else NULL)
    candidates <- candidates[vapply(candidates, function(x) !is.null(x) && nrow(x), logical(1))]
    if (length(candidates)) candidates[[1]] else data.frame()
  }
  if (!nrow(data)) return(NULL)
  x <- if ("observation" %in% names(data)) "observation" else if ("date" %in% names(data)) "date" else names(data)[1]
  group <- if (".plot_group" %in% names(data)) ".plot_group" else NULL
  labels <- plot_labels_code(plot)
  header <- c("# Readable ggplot2 code generated by policycraft", "library(ggplot2)", "library(dplyr)", "", readable_data_code(data), "")
  aes_group <- if (!is.null(group)) paste0(", group = `", group, "`") else ""
  base <- paste0("chart <- ggplot(chart_data, aes(x = `", x, "`, y = value", aes_group, "))")

  body <- switch(type,
    run = c(
      "median_value <- median(chart_data$value, na.rm = TRUE)", "", base,
      "chart <- chart + geom_line(colour = \"darkgray\", linewidth = 1.2)",
      "chart <- chart + geom_point(colour = \"blue\", size = 2.5)",
      "chart <- chart + geom_hline(yintercept = median_value, colour = \"blue\", linewidth = 1)",
      "chart <- chart + annotate(\"text\", x = min(chart_data[[1]], na.rm = TRUE), y = median_value, label = paste(\"Median:\", round(median_value, 2)), vjust = -0.7, hjust = 0)"
    ),
    line = c(base, "chart <- chart + geom_line(colour = \"steelblue\", linewidth = 1.3)", "chart <- chart + geom_point(colour = \"steelblue\", size = 3.5)"),
    bar = c(
      "chart <- ggplot(chart_data, aes(x = reorder(`.plot_group`, value), y = value, fill = `.plot_group`))",
      "chart <- chart + geom_col(width = 0.7, alpha = 0.8)",
      "chart <- chart + geom_text(aes(label = round(value, 2)), hjust = -0.1, fontface = \"bold\")",
      "chart <- chart + coord_flip() + guides(fill = \"none\")"
    ),
    expectation = c(
      "# The limit and signal columns below are the values calculated by Policycraft.", base,
      "chart <- chart + geom_line(colour = \"darkgray\", linewidth = 1.2)",
      "chart <- chart + geom_point(aes(colour = sigma_signals), size = 2.5)",
      if ("emp_cl_orig" %in% names(data)) c(
        "chart <- chart + geom_line(aes(y = ifelse(`.chart_x` < recalc_date, emp_cl_orig, NA)), colour = \"blue\")",
        "chart <- chart + geom_line(aes(y = ifelse(`.chart_x` >= recalc_date, emp_cl_recalc, NA)), colour = \"green\")",
        "chart <- chart + geom_line(aes(y = ifelse(`.chart_x` < recalc_date, emp_ucl_orig, NA)), colour = \"red\")",
        "chart <- chart + geom_line(aes(y = ifelse(`.chart_x` < recalc_date, emp_lcl_orig, NA)), colour = \"red\")",
        "chart <- chart + geom_line(aes(y = ifelse(`.chart_x` >= recalc_date, emp_ucl_recalc, NA)), colour = \"red\", linetype = \"dashed\")",
        "chart <- chart + geom_line(aes(y = ifelse(`.chart_x` >= recalc_date, emp_lcl_recalc, NA)), colour = \"red\", linetype = \"dashed\")",
        "chart <- chart + geom_vline(xintercept = unique(chart_data$recalc_date), colour = \"purple\", linetype = \"dotted\")",
        paste0("chart <- chart + annotate(\"text\", x = min(chart_data$`", x, "`), y = chart_data$emp_cl_orig[1], label = paste0(\"Original CL (\", round(chart_data$emp_cl_orig[1], 2), \")\"), colour = \"blue\", size = 4, fontface = \"bold\", hjust = 0, vjust = -0.8)"),
        paste0("chart <- chart + annotate(\"text\", x = unique(chart_data$recalc_date), y = chart_data$emp_cl_recalc[1], label = paste0(\"Recalculated CL (\", round(chart_data$emp_cl_recalc[1], 2), \")\"), colour = \"green4\", size = 4, fontface = \"bold\", hjust = 0, vjust = -0.8)"),
        paste0("chart <- chart + annotate(\"text\", x = min(chart_data$`", x, "`), y = chart_data$emp_ucl_orig[1], label = paste0(\"Original UCL (\", round(chart_data$emp_ucl_orig[1], 2), \")\"), colour = \"red\", hjust = 0, vjust = -0.6)"),
        paste0("chart <- chart + annotate(\"text\", x = min(chart_data$`", x, "`), y = chart_data$emp_lcl_orig[1], label = paste0(\"Original LCL (\", round(chart_data$emp_lcl_orig[1], 2), \")\"), colour = \"red\", hjust = 0, vjust = 1.4)"),
        paste0("chart <- chart + annotate(\"text\", x = unique(chart_data$recalc_date), y = chart_data$emp_ucl_recalc[1], label = paste0(\"Recalculated UCL (\", round(chart_data$emp_ucl_recalc[1], 2), \")\"), colour = \"red\", hjust = 0, vjust = -0.6)"),
        paste0("chart <- chart + annotate(\"text\", x = unique(chart_data$recalc_date), y = chart_data$emp_lcl_recalc[1], label = paste0(\"Recalculated LCL (\", round(chart_data$emp_lcl_recalc[1], 2), \")\"), colour = \"red\", hjust = 0, vjust = 1.4)")
      ) else c(
        "chart <- chart + geom_line(aes(y = emp_cl), colour = \"blue\")",
        "chart <- chart + geom_line(aes(y = emp_ucl), colour = \"red\")",
        "chart <- chart + geom_line(aes(y = emp_lcl), colour = \"red\")",
        paste0("chart <- chart + annotate(\"text\", x = min(chart_data$`", x, "`), y = chart_data$emp_cl[1], label = paste0(\"CL (\", round(chart_data$emp_cl[1], 2), \")\"), colour = \"blue\", size = 4, fontface = \"bold\", hjust = 0, vjust = -0.8)"),
        paste0("chart <- chart + annotate(\"text\", x = min(chart_data$`", x, "`), y = chart_data$emp_ucl[1], label = paste0(\"UCL (\", round(chart_data$emp_ucl[1], 2), \")\"), colour = \"red\", size = 4, fontface = \"bold\", hjust = 0, vjust = -0.6)"),
        paste0("chart <- chart + annotate(\"text\", x = min(chart_data$`", x, "`), y = chart_data$emp_lcl[1], label = paste0(\"LCL (\", round(chart_data$emp_lcl[1], 2), \")\"), colour = \"red\", size = 4, fontface = \"bold\", hjust = 0, vjust = 1.4)")
      ),
      "chart <- chart + scale_colour_manual(values = c(`TRUE` = \"red\", `FALSE` = \"blue\"))"
    ),
    trended = c(
      "# Refit the trend so the main statistical construction is visible and editable.",
      paste0("chart_data$trend_position <- as.numeric(chart_data$`", x, "` - min(chart_data$`", x, "`))"),
      "trend_model <- lm(value ~ trend_position, data = chart_data)",
      "chart_data$trended_cl <- predict(trend_model)",
      "trend_sigma <- sd(residuals(trend_model), na.rm = TRUE) / 1.128",
      "chart_data$trended_ucl <- chart_data$trended_cl + 3 * trend_sigma",
      "chart_data$trended_lcl <- chart_data$trended_cl - 3 * trend_sigma", "", base,
      "chart <- chart + geom_line(colour = \"darkgray\", linewidth = 1.2)",
      "chart <- chart + geom_point(aes(colour = sigma_signals), size = 2.5)",
      "chart <- chart + geom_line(aes(y = trended_cl), colour = \"blue\")",
      "chart <- chart + geom_line(aes(y = trended_ucl), colour = \"red\", linetype = \"dotted\")",
      "chart <- chart + geom_line(aes(y = trended_lcl), colour = \"red\", linetype = \"dotted\")",
      paste0("chart <- chart + annotate(\"text\", x = min(chart_data$`", x, "`), y = chart_data$trended_cl[1], label = paste0(\"Trended CL (\", round(chart_data$trended_cl[1], 2), \")\"), colour = \"blue\", hjust = 0, vjust = -0.8)"),
      paste0("chart <- chart + annotate(\"text\", x = min(chart_data$`", x, "`), y = chart_data$trended_ucl[1], label = paste0(\"Trended UCL (\", round(chart_data$trended_ucl[1], 2), \")\"), colour = \"red\", hjust = 0, vjust = -0.6)"),
      paste0("chart <- chart + annotate(\"text\", x = min(chart_data$`", x, "`), y = chart_data$trended_lcl[1], label = paste0(\"Trended LCL (\", round(chart_data$trended_lcl[1], 2), \")\"), colour = \"red\", hjust = 0, vjust = 1.4)"),
      "chart <- chart + scale_colour_manual(values = c(`TRUE` = \"red\", `FALSE` = \"blue\"))"
    ),
    cohort = c(base, "chart <- chart + geom_line(colour = \"#2E86AB\", linewidth = 1.5)", "chart <- chart + geom_point(colour = \"#A23B72\", size = 3.5)")
  )
  axis_code <- if (inherits(data[[x]], "Date")) {
    c(
      "date_span <- as.numeric(diff(range(chart_data$date, na.rm = TRUE)))",
      "date_breaks <- if (date_span > 1825) \"1 year\" else if (date_span > 365) \"6 months\" else if (date_span > 90) \"1 month\" else \"1 week\"",
      "date_labels <- if (all(format(chart_data$date, \"%m-%d\") == \"01-01\")) \"%Y\" else \"%Y-%m-%d\"",
      "chart <- chart + scale_x_date(date_breaks = date_breaks, date_labels = date_labels, expand = expansion(mult = c(0.05, 0.15)))"
    )
  } else if (is.numeric(data[[x]])) {
    paste0("chart <- chart + scale_x_continuous(breaks = sort(unique(chart_data$`", x, "`)))")
  } else {
    NULL
  }
  c(
    header, body, "", "# Match the graduations used in the Policycraft app.",
    axis_code, "", paste0("chart <- chart + ", labels),
    "chart <- chart + policycraft::policycraft_chart_theme()",
    "chart <- chart + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())",
    "", "chart"
  )
}

mapping_code <- function(mapping) {
  if (is.null(mapping) || !length(mapping)) return(NULL)
  entries <- vapply(names(mapping), function(name) {
    expression <- rlang::get_expr(mapping[[name]])
    paste0(name, " = ", paste(deparse(expression, width.cutoff = 120L), collapse = " "))
  }, "")
  paste0("ggplot2::aes(", paste(entries, collapse = ", "), ")")
}

geom_function <- function(layer) {
  functions <- c(
    GeomCol = "ggplot2::geom_col",
    GeomHline = "ggplot2::geom_hline",
    GeomLine = "ggplot2::geom_line",
    GeomPoint = "ggplot2::geom_point",
    GeomRichText = "ggtext::geom_richtext",
    GeomSegment = "ggplot2::geom_segment",
    GeomText = "ggplot2::geom_text",
    GeomVline = "ggplot2::geom_vline"
  )
  match <- intersect(class(layer$geom), names(functions))
  if (!length(match)) return(NA_character_)
  unname(functions[[match[1]]])
}

layer_parameter_code <- function(layer) {
  # aes_params are the explicit fixed aesthetics supplied by the app. Retain a
  # small set of meaningful geom parameters while dropping ggplot2 defaults.
  keep_geom <- c(
    "arrow", "check_overlap", "label.padding", "label.margin", "label.r",
    "lineend", "linejoin", "parse"
  )
  parameters <- c(
    layer$aes_params,
    layer$geom_params[intersect(names(layer$geom_params), keep_geom)]
  )
  parameters <- parameters[!duplicated(names(parameters))]
  parameters <- parameters[!vapply(parameters, is.null, logical(1))]
  parameters <- parameters[!vapply(parameters, is.function, logical(1))]
  if (!length(parameters)) return(character(0))
  vapply(names(parameters), function(name) {
    paste0(name, " = ", code_value(parameters[[name]]))
  }, "")
}

plot_labels_code <- function(plot) {
  wanted <- c("title", "subtitle", "caption", "x", "y")
  labels <- plot$labels[intersect(wanted, names(plot$labels))]
  labels <- labels[vapply(labels, function(x) is.null(x) ||
    (is.atomic(x) && length(x) == 1L), logical(1))]
  if (!length(labels)) return(NULL)
  values <- vapply(names(labels), function(name) {
    paste0(name, " = ", code_value(labels[[name]]))
  }, "")
  paste0("ggplot2::labs(\n    ", paste(values, collapse = ",\n    "), "\n  )")
}

resolved_layer_export <- function(layer, plot, layer_number) {
  data <- if (inherits(layer$data, "waiver")) plot$data else layer$data
  data <- as.data.frame(data)
  mapping <- if (isTRUE(layer$inherit.aes)) plot$mapping else list()
  for (name in names(layer$mapping)) mapping[[name]] <- layer$mapping[[name]]

  exported_mapping <- character(0)
  if (length(mapping)) {
    for (name in names(mapping)) {
      value <- tryCatch(
        rlang::eval_tidy(mapping[[name]], data = data),
        error = function(e) NULL
      )
      if (!is.null(value) && (length(value) == 1L || length(value) == nrow(data))) {
        column <- paste0(".layer_", layer_number, "_", name)
        data[[column]] <- rep(value, length.out = nrow(data))
        exported_mapping <- c(exported_mapping, paste0(name, " = ", column))
      } else {
        expression <- rlang::get_expr(mapping[[name]])
        exported_mapping <- c(
          exported_mapping,
          paste0(name, " = ", paste(deparse(expression, width.cutoff = 120L), collapse = " "))
        )
      }
    }
  }

  list(
    data = data,
    mapping = if (length(exported_mapping)) {
      paste0("ggplot2::aes(", paste(exported_mapping, collapse = ", "), ")")
    } else {
      NULL
    }
  )
}

plot_scale_code <- function(plot) {
  data <- if (inherits(plot$data, "waiver")) data.frame() else plot$data
  mapping_names <- names(plot$mapping)
  x_name <- if ("x" %in% mapping_names) {
    as.character(rlang::get_expr(plot$mapping$x))
  } else {
    NULL
  }
  x_values <- if (!is.null(x_name) && x_name %in% names(data)) data[[x_name]] else NULL

  calls <- character(0)
  if (inherits(x_values, "Date")) {
    calls <- c(calls, "ggplot2::scale_x_date(date_labels = \"%Y-%m-%d\")")
  } else if (is.numeric(x_values)) {
    calls <- c(calls, paste0(
      "ggplot2::scale_x_continuous(breaks = ",
      code_value(sort(unique(x_values[is.finite(x_values)]))), ")"
    ))
  }

  colour_mapped <- "colour" %in% mapping_names || "color" %in% mapping_names ||
    any(vapply(plot$layers, function(layer) {
      any(c("colour", "color") %in% names(layer$mapping))
    }, logical(1)))
  fill_mapped <- "fill" %in% mapping_names || any(vapply(plot$layers, function(layer) {
    "fill" %in% names(layer$mapping)
  }, logical(1)))
  if (colour_mapped) {
    calls <- c(calls, "ggplot2::scale_colour_manual(values = c(\"TRUE\" = \"red\", \"FALSE\" = \"blue\"))")
  }
  if (fill_mapped) {
    calls <- c(calls, "ggplot2::scale_fill_brewer(palette = \"Set2\")")
  }
  calls
}

# Create compact, readable ggplot2 source. Chart and layer data are emitted as
# ordinary data frames; reactive environments and other Shiny session state are
# deliberately excluded.
ggplot_code_lines <- function(plot, chart_name = "chart") {
  if (!inherits(plot, "ggplot")) {
    stop("The chart code download requires a ggplot object.", call. = FALSE)
  }
  semantic <- semantic_chart_code(plot, chart_name)
  if (!is.null(semantic)) return(semantic)

  chart_data <- if (inherits(plot$data, "waiver")) data.frame() else as.data.frame(plot$data)
  lines <- c(
    "# Generated by policycraft from the chart currently shown in the app.",
    "# The data and each ggplot2 layer are written explicitly for editing and learning.",
    "# Paste this file into a Quarto code cell, or source it from your report.",
    "",
    "library(ggplot2)",
    if (any(vapply(plot$layers, function(layer) inherits(layer$geom, "GeomRichText"), logical(1)))) "library(ggtext)" else NULL,
    "",
    paste0("# Chart: ", chart_name),
    "chart_data <- ",
    code_value(chart_data),
    ""
  )

  # Each layer receives explicit, resolved aesthetics below. Keeping the base
  # ggplot unmapped prevents quosure environments from leaking into the script.
  lines <- c(lines, "chart <- ggplot2::ggplot(data = chart_data)")

  layer_data_index <- 0L
  for (layer_number in seq_along(plot$layers)) {
    layer <- plot$layers[[layer_number]]
    geom <- geom_function(layer)
    if (is.na(geom)) next
    layer_data_index <- layer_data_index + 1L
    data_name <- paste0("layer_data_", layer_data_index)
    resolved <- resolved_layer_export(layer, plot, layer_number)
    lines <- c(
      lines,
      "",
      paste0("# Layer ", layer_number, ": ", sub(".*::", "", geom)),
      paste0(data_name, " <- "),
      code_value(resolved$data)
    )
    arguments <- c(paste0("data = ", data_name))
    if (!is.null(resolved$mapping)) arguments <- c(arguments, resolved$mapping)
    arguments <- c(arguments, "inherit.aes = FALSE")
    arguments <- c(arguments, layer_parameter_code(layer))
    layer_call <- paste0(geom, "(", paste(arguments, collapse = ", "), ")")
    lines <- c(lines, paste0("chart <- chart + ", layer_call))
  }

  additions <- c(
    plot_scale_code(plot),
    plot_labels_code(plot),
    "policycraft::policycraft_chart_theme()",
    "ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))"
  )
  lines <- c(
    lines,
    "",
    "# Scales, labels, and theme. These are safe places to customize the chart.",
    vapply(additions, function(addition) paste0("chart <- chart + ", addition), ""),
    "",
    "chart"
  )
  lines
}

chart_plot_ui <- function(id, height = "600px") {
  ns <- shiny::NS(id)
  shiny::plotOutput(ns("plot"), height = height)
}

chart_plot_server <- function(id, plot_reactive) {
  shiny::moduleServer(id, function(input, output, session) {
    output$plot <- shiny::renderPlot(plot_reactive())
  })
}

chart_download_server <- function(
  id,
  plot_reactive,
  filename_prefix,
  width = CHART_EXPORT_WIDTH_IN,
  height = CHART_EXPORT_HEIGHT_IN
) {
  shiny::moduleServer(id, function(input, output, session) {
    output$png <- shiny::downloadHandler(
      filename = function() paste0(filename_prefix, "_", Sys.Date(), ".png"),
      content = function(file) {
        ggplot2::ggsave(
          file,
          plot = plot_reactive(),
          device = "png",
          width = width,
          height = height,
          dpi = CHART_EXPORT_DPI,
          bg = "white"
        )
      }
    )

    output$svg <- shiny::downloadHandler(
      filename = function() paste0(filename_prefix, "_", Sys.Date(), ".svg"),
      content = function(file) {
        ggplot2::ggsave(
          file,
          plot = plot_reactive(),
          device = "svg",
          width = width,
          height = height,
          bg = "white"
        )
      }
    )

    output$pdf <- shiny::downloadHandler(
      filename = function() paste0(filename_prefix, "_", Sys.Date(), ".pdf"),
      content = function(file) {
        tryCatch(
          ggplot2::ggsave(
            file,
            plot = plot_reactive(),
            device = grDevices::cairo_pdf,
            width = width,
            height = height,
            bg = "white"
          ),
          error = function(e) {
            ggplot2::ggsave(
              file,
              plot = plot_reactive(),
              device = "pdf",
              width = width,
              height = height,
              bg = "white"
            )
          }
        )
      }
    )

    output$code <- shiny::downloadHandler(
      filename = function() paste0(filename_prefix, "_", Sys.Date(), ".R"),
      content = function(file) {
        writeLines(
          ggplot_code_lines(plot_reactive(), chart_name = filename_prefix),
          con = file,
          useBytes = TRUE
        )
      },
      contentType = "text/plain"
    )
  })
}
